### ISSUE TITLE
Crashes on MacOS when creating a pixel display

### ISSUE THREAD

**Issue by mikaeleiman** [jdryg/dls-schematics#23]
DLS_v0.16.2_macos_x64_2018_12_29

Running on MacOS 10.14.2 on a MacBook Pro.

[DLS.log](https://github.com/jdryg/dls-schematics/files/2795861/DLS.log)

**Comment by jdryg** [comment]
Thanks for the crash report and sorry for the inconvenience. I probably missed it when testing on macos. Will check it asap and report back. In case I'm unable to reproduce the bug I'll upload a debug version of the app with extended logging enabled to see if there's something there.

**Comment by jdryg** [comment]
I was able to reproduce the bug. Will look for the actual cause and hopefully it will be fixed in the next update. 
Thanks again for the crash report. Hope it doesn't prevents you from trying out the rest of the functionality.

**Comment by jdryg** [comment]
I uploaded v0.16.3 on itch.io. Can you please try it out and tell me if it works now?

**Comment by mikaeleiman** [comment]
Doesn't crash now, thanks!
