### ISSUE TITLE
Bug in output component

### ISSUE THREAD

**Issue by Cthutu** [jdryg/dls-schematics#25]
![image](https://user-images.githubusercontent.com/348614/54366090-72409180-4646-11e9-87fe-6c07c62edf02.png)

From the image above, there seems to be a bug in the output.  The inputs to the merger are all different but the output remains a 'U' and not the unsigned value I'd expect.

You can contact me at mattie.davies@gmail.com if you require a schematic to debug this.

**Comment by jdryg** [comment]
I think you forgot to connect the clock to the last column of registers :)

A wire merger will produce a non-undefined value if **all** its inputs are non-undefined. In your case inputs/bits 3,7,11 and 15 are undefined. That's why the merger's output is undefined.

Hope that helps.

**Comment by Cthutu** [comment]
You're absolutely right!  Don't know how I missed that.  Sorry for wasting your time.

**Comment by jdryg** [comment]
No problem :) Happy to help. 

Don't hesitate to post any other issues you might encounter.
