### ISSUE TITLE
Crashes when going to sandbox -> menu -> main menu -> sandbox

### ISSUE THREAD

**Issue by hardistones** [jdryg/dls-schematics#27]
DLS version: **v0.17.1_Win_x64_2022_02_17**

Steps to reproduce:
1. Open game.
2. Select Sandbox (goes to sandbox/workspace screen)
3. Click on Hamburger Menu button of the top panel (goes to the grey menu screen)
4. Select Main Menu (goes to the green menu screen)
5. Select Sandbox (this is where the game will crash).

**Comment by jdryg** [comment]
Thanks for the detailed bug report. I'll try to reproduce and fix it asap.

**Comment by jdryg** [comment]
Should be fixed in latest 0.17.2

**Comment by hardistones** [comment]
Thanks.
